---
title: "Genomics"
# linktitle: "1. Introduction to RStudio and Images"
date: "2025-09-03"
class_date: "2025-09-03"
draft: false
output:
  blogdown::html_page:
    toc: false
menu:
  class:
    parent: Class sessions
    weight: 3
type: docs
weight: 3
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

## The Biology and Genetics of Cells and Organisms

<a href="../../slides/02a_Biology/02a_Biology.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/02a_Biology/02a_Biology.html#1')
```

<a href="../../slides/02a_Biology/02b_DNA.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/02a_Biology/02b_DNA.html#1')
```

<a href="../../slides/02a_Biology/02c_Genes.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/02a_Biology/02c_Genes.html#1')
```


<a href="../../slides/03a_Genomic_technologies/02_Genomics.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/03a_Genomic_technologies/02_Genomics.html#1')
```

<a href="../../slides/03a_Genomic_technologies/02b_Human_Genome.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/03a_Genomic_technologies/02b_Human_Genome.html#1')
```

<a href="../../slides/03b_Genomic_resources/01a_Genomic_formats.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/03b_Genomic_resources/01a_Genomic_formats.html#1')
```

<a href="../../slides/03b_Genomic_resources/02a_Genomic_resources.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/03b_Genomic_resources/02a_Genomic_resources.html#1')
```
