---
title: "RNA-seq"
# linktitle: "1. Introduction to RStudio and Images"
date: "2025-09-22"
class_date: "2025-09-22"
draft: false
output:
  blogdown::html_page:
    toc: false
menu:
  class:
    parent: Class sessions
    weight: 5
type: docs
weight: 5
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

## RNA-seq sequencing

<a href="../../slides/06_RNA-seq/01_RNA-seq_overview.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/06_RNA-seq/01_RNA-seq_overview.html#1')
```

<a href="../../slides/06_RNA-seq/02_RNA-seq_expdesign.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/06_RNA-seq/02_RNA-seq_expdesign.html#1')
```

<a href="../../slides/06_RNA-seq/03_RNA-seq_qc_alignment.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/06_RNA-seq/03_RNA-seq_qc_alignment.html#1')
```

<a href="../../slides/06_RNA-seq/04_RNA-seq_quantification.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/06_RNA-seq/04_RNA-seq_quantification.html#1')
```

## Normalization

<a href="../../slides/06_RNA-seq/05_RNA-seq_normalization.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/06_RNA-seq/05_RNA-seq_normalization.html#1')
```

### Code examples

- Demo00_log2, <a href="../../slides/04_Bioconductor/lab/Demo00_log2.Rmd" target="_blank">Rmd</a>, <a href="../../slides/06_RNA-seq/lab/Demo00_log2.html" target="_blank">HTML</a>
- Demo01_loess, <a href="../../slides/04_Bioconductor/lab/Demo01_loess.Rmd" target="_blank">Rmd</a>, <a href="../../slides/06_RNA-seq/lab/Demo01_loess.html" target="_blank">HTML</a>
- Demo02_quantile_norm, <a href="../../slides/04_Bioconductor/lab/Demo02_quantile_norm.Rmd" target="_blank">Rmd</a>, <a href="../../slides/06_RNA-seq/lab/Demo02_quantile_norm.html" target="_blank">HTML</a>

