---
title: "Differential Expression"
# linktitle: "1. Introduction to RStudio and Images"
date: "2025-10-06"
class_date: "2025-10-06"
draft: false
output:
  blogdown::html_page:
    toc: false
menu:
  class:
    parent: Class sessions
    weight: 6
type: docs
weight: 6
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

## Differential expression

<a href="../../slides/07a_DiffExpr/07a_Intro.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/07a_DiffExpr/07a_Intro.html#1')
```

<a href="../../slides/07a_DiffExpr/07b_design_matrices.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/07a_DiffExpr/07b_design_matrices.html#1')
```

<a href="../../slides/07a_DiffExpr/07c_multipletesting.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/07a_DiffExpr/07c_multipletesting.html#1')
```

<a href="../../slides/07a_DiffExpr/07d_Overview_stats.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/07a_DiffExpr/07d_Overview_stats.html#1')
```

<a href="../../slides/07a_DiffExpr/07e_limma.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/07a_DiffExpr/07e_limma.html#1')
```

<a href="../../slides/07a_DiffExpr/07f_edgeR.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/07a_DiffExpr/07f_edgeR.html#1')
```

<a href="../../slides/07a_DiffExpr/07j_DESeq2.html#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/07a_DiffExpr/07j_DESeq2.html#1')
```

### Code examples

- multitest.Rmd, <a href="../../slides/07a_DiffExpr/lab/multitest.Rmd" target="_blank">Rmd</a>, <a href="../../slides/07a_DiffExpr/lab/multitest.html" target="_blank">HTML</a>

- permutations.Rmd, <a href="../../slides/07a_DiffExpr/lab/permutations.Rmd" target="_blank">Rmd</a>, <a href="../../slides/07a_DiffExpr/lab/permutations.html" target="_blank">HTML</a>
